env:
  global:
    - CC_TEST_REPORTER_ID=090889fc04d641494d657317c3394d44e9f32bbb5993d290d30d40e8b0e363cb
    - COVERALLS_REPO_TOKEN=9QeYZZ3d5p1HAODTrPxSxioqSsHreONXv
    - TEAMWORK_DATABASE_USER=iopnxytv
    - TEAMWORK_DATABASE_HOST=salt.db.elephantsql.com
    - TEAMWORK_DATABASE=iopnxytv
    - TEAMWORK_DATABASE_PASSWORD=gYVfD_df_4vqLi87UTx6u8JPKz8jkhdF
    - TEAMWORK_DATABASE_USER_TEST=wubncfbz
    - TEAMWORK_DATABASE_HOST_TEST=salt.db.elephantsql.com
    - TEAMWORK_DATABASE_TEST=wubncfbz
    - TEAMWORK_DATABASE_PASSWORD_TEST=8t0VtXbVQQmAIfnmax182SETdN6RgLmp
    - NODE_ENV=testing

language: node_js
node_js: "node"

services:
  - postgresql

cache:
  directories:
    - "node_modules"

before_script:
  - npm install
  - npm install nyc -g
  - psql -c 'create database iopnxytv_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coverage
